pip install git+https://github.com/buaahsh/fairseq.git@moe
pip install git+https://github.com/shumingma/infinibatch.git
pip install iopath
pip install numpy==1.23.0
pip install tiktoken
pip install boto3
pip install sentencepiece
pip install scikit-learn
pip install datasets
pip install timm===0.4.12